language: go
sudo: false
go:
  - 1.7
  - 1.8
  - tip

go_import_path: github.com/danielkov/log0

before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -v -cover -race -coverprofile=/tmp/coverage.out
  - $GOPATH/bin/goveralls -coverprofile=/tmp/coverage.out -service=travis-ci